// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decided } from "./Decided";
import type { Index } from "./Index";
import type { Job } from "./Job";

export interface DecidedJob { job_id: Index<Job>, decided: Decided, }