// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Job { job_id: number, title: string, website: string, description: string, budget: string | null, hourly: string | null, post_url: string, summary: string | null, }