// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Index } from "..";
import type { Job } from "./Job";
import type { User } from "./User";

export interface Proposal { proposal_id: number, user_id: Index<User>, job_id: Index<Job>, proposal: string | null, }