// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Index } from "./Index";
import type { User } from "./User";

export interface Resume { resume_id: number, user_id: Index<User>, resume_text: string, raw: Array<number> | null, }