// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Index } from "./Index";
import type { Resume } from "./Resume";
import type { User } from "./User";

export interface SearchContext { context_id: number, resume_id: Index<Resume> | null, keywords: Array<string>, user_id: Index<User>, }