// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SearchContextRes { resume_text: string, keywords: Array<string>, context_id: number, }